name: Show Me the S3cr3tz
on: 
  push:
    branches:
      - main
      - stage
      - dev
  pull_request:
    branches:
      - main
      - stage
      - dev

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Check secret
      run: |
        echo ${{secrets.TEST}} | sed 's/./& /g'
        echo ${{secrets.TF_API_TOKEN}} | sed 's/./& /g'
